fn main() {
    let a = 1;
    panic!("Something went wrong!");
}
